### ISSUE TITLE
Fatal error on plugin activation

### ISSUE THREAD

**Issue by markfenske84** [XennisBlog/awesome-cluster-map#2]
When trying to activate this plugin, I get this error:

`Warning: require_once(/app/public/wp-content/plugins/wordpress-awesome-cluster-map-master/wordpress-awesome-cluster-map-master.helper.php): failed to open stream: No such file or directory in /app/public/wp-content/plugins/wordpress-awesome-cluster-map-master/awesome-cluster-map.php on line 19 Fatal error: require_once(): Failed opening required '/app/public/wp-content/plugins/wordpress-awesome-cluster-map-master/wordpress-awesome-cluster-map-master.helper.php' (include_path='.:/usr/share/php:/www/wp-content/pear') in /app/public/wp-content/plugins/wordpress-awesome-cluster-map-master/awesome-cluster-map.php on line 19`

I've tried in multiple different WP scenarios, current client staging site and fresh blank WP install.

**Comment by Xennis** [comment]
Seem like it fails here:
https://github.com/Xennis/wordpress-awesome-cluster-map/blob/a1e5655488f37421d0d33f7efa67c5cd5550bd75/awesome-cluster-map.php#L19

Can you try to rename the directory `wordpress-awesome-cluster-map-master` (in the `plugins` directory) to `awesome-cluster-map` so that it fits the text domain:

https://github.com/Xennis/wordpress-awesome-cluster-map/blob/a1e5655488f37421d0d33f7efa67c5cd5550bd75/awesome-cluster-map.php#L8

@markfenske84 Does it work then?

**Comment by Xennis** [comment]
No response for a long time. Close issue.
